people_list = [
    {"name": "Virat Kohli", "followers": 120000000, "description": "Indian cricketer, former captain of Indian cricket team", "country": "India"},
    {"name": "Priyanka Chopra", "followers": 64000000, "description": "Indian actress and producer", "country": "India"},
    {"name": "Cristiano Ronaldo", "followers": 450000000, "description": "Professional footballer, plays for Manchester United", "country": "Portugal"},
    {"name": "Disha Patani", "followers": 46000000, "description": "Indian actress and model", "country": "India"},
    {"name": "MS Dhoni", "followers": 35000000, "description": "Former Indian cricket captain", "country": "India"},
    {"name": "Lionel Messi", "followers": 280000000, "description": "Professional footballer, plays for Paris Saint-Germain", "country": "Argentina"},
    {"name": "Deepika Padukone", "followers": 56000000, "description": "Indian actress and producer", "country": "India"},
    {"name": "Rohit Sharma", "followers": 22000000, "description": "Indian cricketer, vice-captain of Indian cricket team", "country": "India"},
    {"name": "Neymar Jr.", "followers": 150000000, "description": "Professional footballer, plays for Paris Saint-Germain", "country": "Brazil"},
    {"name": "Alia Bhatt", "followers": 60000000, "description": "Indian actress and singer", "country": "India"},
    {"name": "Kohli's Fan Page", "followers": 1000000, "description": "Dedicated to the biggest Virat Kohli fan", "country": "India"},
    {"name": "Rishabh Pant", "followers": 8000000, "description": "Indian cricketer, wicketkeeper-batsman", "country": "India"},
    {"name": "Mohamed Salah", "followers": 38000000, "description": "Professional footballer, plays for Liverpool", "country": "Egypt"},
    {"name": "Shah Rukh Khan", "followers": 40000000, "description": "Indian actor and film producer", "country": "India"},
    {"name": "Hardik Pandya", "followers": 16000000, "description": "Indian cricketer, all-rounder", "country": "India"},
    {"name": "Anushka Sharma", "followers": 31000000, "description": "Indian actress and film producer", "country": "India"},
    {"name": "Sachin Tendulkar", "followers": 22000000, "description": "Former Indian cricketer, widely regarded as one of the greatest batsmen in the history of cricket", "country": "India"},
    {"name": "Amitabh Bachchan", "followers": 43000000, "description": "Indian film actor, film producer, television host, occasional playback singer and former politician", "country": "India"},
    {"name": "Suresh Raina", "followers": 16000000, "description": "Indian cricketer, left-handed middle-order batsman", "country": "India"},
    {"name": "Dwayne Johnson", "followers": 270000000, "description": "Actor and former professional wrestler", "country": "USA"},
    {"name": "Ranveer Singh", "followers": 36000000, "description": "Indian actor who appears in Hindi films", "country": "India"},
    {"name": "Yuvraj Singh", "followers": 12000000, "description": "Indian former cricketer who played in all formats for the Indian cricket team", "country": "India"},
    {"name": "David Beckham", "followers": 67000000, "description": "Former professional footballer, plays for Manchester United and Real Madrid", "country": "England"},
    {"name": "Salman Khan", "followers": 49000000, "description": "Indian film actor, producer, occasional singer and television personality", "country": "India"},
    {"name": "Mahendra Singh Dhoni", "followers": 21000000, "description": "Former Indian cricketer, former captain of the Indian national cricket team", "country": "India"},
    {"name": "Sonam Kapoor", "followers": 31000000, "description": "Indian film actress", "country": "India"},
    {"name": "Abhishek Bachchan", "followers": 11000000, "description": "Indian film actor and film producer known for his work in Hindi cinema", "country": "India"},
    {"name": "Rohit Sharma Fans", "followers": 900000, "description": "Fan page dedicated to Rohit Sharma, Indian cricketer", "country": "India"},
    {"name": "Leonardo DiCaprio", "followers": 49000000, "description": "American actor, film producer, and environmentalist", "country": "USA"},
    {"name": "Ravindra Jadeja", "followers": 11000000, "description": "Indian cricketer, all-rounder", "country": "India"},
    {"name": "Saina Nehwal", "followers": 14000000, "description": "Indian badminton player", "country": "India"},
    {"name": "Kareena Kapoor Khan", "followers": 33000000, "description": "Indian actress who appears in Hindi films", "country": "India"},
    {"name": "Chris Hemsworth", "followers": 46000000, "description": "Australian actor", "country": "Australia"},
    {"name": "Manish Pandey", "followers": 1000000, "description": "Indian cricketer, batsman", "country": "India"},
    {"name": "Akshay Kumar", "followers": 40000000, "description": "Indian-born Canadian actor, film producer, and television personality", "country": "India"},
    {"name": "Chris Evans", "followers": 38000000, "description": "American actor", "country": "USA"},
    {"name": "Shikhar Dhawan", "followers": 8000000, "description": "Indian cricketer, opening batsman", "country": "India"},
    {"name": "Chris Pratt", "followers": 36000000, "description": "American actor", "country": "USA"},
    {"name": "Gautam Gambhir", "followers": 8000000, "description": "Indian politician and former cricketer", "country": "India"},
    {"name": "John Cena", "followers": 19000000, "description": "American professional wrestler, actor, and television presenter", "country": "USA"},
    {"name": "Ravi Shastri", "followers": 1200000, "description": "Indian cricket coach and former cricketer", "country": "India"},
    {"name": "Michael Jordan", "followers": 19000000, "description": "Former professional basketball player", "country": "USA"},
    {"name": "Kevin Hart", "followers": 13000000, "description": "American stand-up comedian, actor, and producer", "country": "USA"},
    {"name": "Ricky Ponting", "followers": 2000000, "description": "Australian cricket coach and former cricketer", "country": "Australia"},
    {"name": "Justin Bieber", "followers": 190000000, "description": "Canadian singer-songwriter", "country": "Canada"},
    {"name": "Kevin Durant", "followers": 19000000, "description": "Professional basketball player for the Brooklyn Nets", "country": "USA"},
    {"name": "Serena Williams", "followers": 12000000, "description": "Professional tennis player", "country": "USA"},
    {"name": "Adam Gilchrist", "followers": 1000000, "description": "Former Australian cricketer and commentator", "country": "Australia"},
    {"name": "Usain Bolt", "followers": 10000000, "description": "Jamaican former sprinter", "country": "Jamaica"},
    {"name": "Sanjay Manjrekar", "followers": 2000000, "description": "Former Indian cricketer and commentator", "country": "India"}
]

